### ISSUE TITLE
Storybook Page Title Fix

### ISSUE THREAD

**Issue by aaron-sgy** [ucsb-cs156-s22/STARTER-team03-docs#1]
@pconrad @andrewhlu @kheff16 @andrewhlu

# Overview
Currently, in `docs/_layouts/deafult.html`, the title for the storybook page's title is set as `{{site.repo_name}}-qa-docs`, but it should be `{{site.repo_name}}-docs` because this is for the production page not the qa one. 

## Issue 
I wasn't able to push anything and make a pull request to this repo because I don't have access rights.

**Comment by andrewhlu** [comment]
Thanks for creating the issue, I made the change in ucsb-cs156/demo-spring-react-example so it'll be reflected in all of our assignments going forward, not just team03!
